<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>chessApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\chessApi.Application\chessApi.Application.csproj" />
      <ProjectReference Include="..\chessApi.Infrastructure\chessApi.Infrastructure.csproj" />
    </ItemGroup>

</Project>
